# https://blog.urth.org/2023/03/05/cross-compiling-rust-projects-in-github-actions/
name: Release
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: kressnick25/roast/.github/workflows/test.yml@main
    secrets: inherit

  release:
    name: Release - ${{ matrix.platform.os_name }}
    needs: test
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            script: ./build/build-nix.sh

          - os_name: Windows-x86_64
            os: windows-latest
            script: ./build/build-win.ps1

          - os_name: macOS-arm64
            os: macos-latest
            script: ./build/build-mac.sh

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: rustup
        run: rustup toolchain install ${{ matrix.platform.target }} --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        # shell picked implicitly from runs-on
        run: ${{ matrix.platform.script }}
     
      - uses: fregante/setup-git-user@v2

      - name: Tag latest
        run: |
          git tag --force -a latest -m "Latest release" ${GITHUB_SHA}
          git push --force origin latest

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: "latest"
          prerelease: true
          generate_release_notes: false
          tag_name: latest
          files: "roast*"
