name: Test
on:
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Lint
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  test:
    name: Test Suite
    needs: check
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
          - runner: macos-latest
          - runner: windows-latest
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: rustup
        run: rustup toolchain install stable --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true

      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest

  build:
    name: Build
    needs: check
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
          - runner: macos-latest
          - runner: windows-latest
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Build executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

