name: Test
on:
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: rustup
        run: rustup toolchain install stable --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    needs: check
    strategy:
      matrix:
        node-version: [22.14.0]
        platform:
          - runner: ubuntu-latest
            bin: roast
            env_set: export ROAST_EXE=./roast
          - runner: macos-latest
            bin: roast
            env_set: export ROAST_EXE=./roast
          - runner: windows-latest
            bin: roast.exe
            env_set: $env:ROAST_EXE='./roast.exe'
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: rustup
        run: rustup toolchain install stable --profile minimal

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Copy executable to test dir
        run: cp target/release/${{ matrix.platform.bin }} tests/${{ matrix.platform.bin }}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install test dependencies
        working-directory: ./tests
        run: npm ci

      - name: Run test suite
        working-directory: ./tests
        run: |
          ${{ matrix.platform.env_set }}
          npm run test
